### ISSUE TITLE
fast_motion

### ISSUE THREAD

**Issue by lhnynl** [wencheng256/SiamBAN-ACM#10]
作者您好，我发现到在test中，您的代码添加了fast_motion处理，想知道这一操作对于性能的影响？

**Comment by wencheng256** [comment]
您好  该操作对于部分移动较快的小物体可以增强鲁棒性。能增强VOT19/20/21的部分视频的稳定性，对于其他数据集影响不大

**Comment by wencheng256** [comment]
可以自己试一下

**Comment by lhnynl** [comment]
好的，谢谢您的回复。
