### ISSUE TITLE
Raw Results

### ISSUE THREAD

**Issue by Yang428** [wencheng256/SiamBAN-ACM#17]
您好，请问可以提供下SiamRPN++ACM在OTB100和Lasot上的raw results吗？有个审稿人让我加个对比结果图，您readme里提供的链接好像只有SiamBAN-ACM的raw results. 万分感谢！

**Comment by wencheng256** [comment]
您好 感谢关注。 您直接放SiamBAN-ACM的raw results吧 本文的主要方法是SiamBAN-ACM  
SiamRPN++ACM是用来展示方法通用性的属于自对比实验性质，相关raw result我们也并没特意保存
