### ISSUE TITLE
Request for raw results on LaSOT dataset

### ISSUE THREAD

**Issue by BruthYU** [wencheng256/SiamBAN-ACM#2]
One of my reviewers asked me to compare my method with newly proposed trackers on LaSOT dataset, including SiamCAR, SiamBAN and SiamBAN-ACM. Could you please share me with the raw results?

**Comment by wencheng256** [comment]
It has been released

**Comment by wencheng256** [comment]
Please refer to the readme.md

**Comment by triumph693** [comment]
> One of my reviewers asked me to compare my method with newly proposed trackers on LaSOT dataset, including SiamCAR, SiamBAN and SiamBAN-ACM. Could you please share me with the raw results?

您是也跑了SiamCAR的代码么，您跑出来的结果是怎样的，您用了几个数据集来训练呢，期待您的回复
