### ISSUE TITLE
论文咨询

### ISSUE THREAD

**Issue by triumph693** [wencheng256/SiamBAN-ACM#5]
<img width="137" alt="1635669495(1)" src="https://user-images.githubusercontent.com/83324302/139574781-cd1e11f9-7add-4bca-b11d-98ee2c46e7a2.png">
作者，您好，我想请问一下，上面卷积得到的两个特征的尺寸不同，尺寸不同的特征是怎么加起来的呢

**Comment by wencheng256** [comment]
可以直接加的 有broadcasting机制

**Comment by triumph693** [comment]
好的，多谢
