### ISSUE TITLE
bbox和model_builder

### ISSUE THREAD

**Issue by xin858466707** [wencheng256/SiamBAN-ACM#7]
![image](https://user-images.githubusercontent.com/84892268/140481996-84834bb7-a0d4-4073-aa35-cf7dae19a29a.png)
这里的bbox代表的是什么，您的model_builder没有完整提供

**Comment by wencheng256** [comment]
test代码中有的，init框的wh

**Comment by xin858466707** [comment]
请问train的bbox是init-box还是gt_box，是不是收敛变慢了，可以问一下你们训练了多少个epoch吗

**Comment by wencheng256** [comment]
是init-box 如果是如果是gtbox就不需要学习了。没有变慢吧 我们也是训练20Epoch
