### ISSUE TITLE
> One of my reviewers asked me to compare my method with newly proposed trackers on LaSOT dataset, including SiamCAR, SiamBAN and SiamBAN-ACM. Could you please share me with the raw results?

### ISSUE THREAD

**Issue by xin858466707** [wencheng256/SiamBAN-ACM#9]
> One of my reviewers asked me to compare my method with newly proposed trackers on LaSOT dataset, including SiamCAR, SiamBAN and SiamBAN-ACM. Could you please share me with the raw results?

您是也跑了SiamCAR的代码么，您跑出来的结果是怎样的，您用了几个数据集来训练呢，期待您的回复

_Originally posted by @triumph693 in https://github.com/wencheng256/SiamBAN-ACM/issues/2#issuecomment-961673598_

**Comment by xin858466707** [comment]
我最近也训了SiamCAR,效果不行，你的呢？

**Comment by wencheng256** [comment]
我没训练过SiamCAR。 SiamBAN的raw result可以在github 他的readme里面找到 ACM的raw result在本仓库的readme可以找到

**Comment by triumph693** [comment]
> 我最近也训了SiamCAR,效果不行，你的呢？

我训练的效果也不好，我觉得是数据集用的少的原因，您觉得是什么原因呢

**Comment by wencheng256** [comment]
您去他们仓库问呀。。。
